// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/cilium.io/v2alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCiliumResolvedPolicies implements CiliumResolvedPolicyInterface
type fakeCiliumResolvedPolicies struct {
	*gentype.FakeClientWithList[*v2alpha1.CiliumResolvedPolicy, *v2alpha1.CiliumResolvedPolicyList]
	Fake *FakeCiliumV2alpha1
}

func newFakeCiliumResolvedPolicies(fake *FakeCiliumV2alpha1, namespace string) ciliumiov2alpha1.CiliumResolvedPolicyInterface {
	return &fakeCiliumResolvedPolicies{
		gentype.NewFakeClientWithList[*v2alpha1.CiliumResolvedPolicy, *v2alpha1.CiliumResolvedPolicyList](
			fake.Fake,
			namespace,
			v2alpha1.SchemeGroupVersion.WithResource("ciliumresolvedpolicies"),
			v2alpha1.SchemeGroupVersion.WithKind("CiliumResolvedPolicy"),
			func() *v2alpha1.CiliumResolvedPolicy { return &v2alpha1.CiliumResolvedPolicy{} },
			func() *v2alpha1.CiliumResolvedPolicyList { return &v2alpha1.CiliumResolvedPolicyList{} },
			func(dst, src *v2alpha1.CiliumResolvedPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v2alpha1.CiliumResolvedPolicyList) []*v2alpha1.CiliumResolvedPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v2alpha1.CiliumResolvedPolicyList, items []*v2alpha1.CiliumResolvedPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
