// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CiliumResolvedPolicyLister helps list CiliumResolvedPolicies.
// All objects returned here must be treated as read-only.
type CiliumResolvedPolicyLister interface {
	// List lists all CiliumResolvedPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ciliumiov2alpha1.CiliumResolvedPolicy, err error)
	// Get retrieves the CiliumResolvedPolicy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ciliumiov2alpha1.CiliumResolvedPolicy, error)
	CiliumResolvedPolicyListerExpansion
}

// ciliumResolvedPolicyLister implements the CiliumResolvedPolicyLister interface.
type ciliumResolvedPolicyLister struct {
	listers.ResourceIndexer[*ciliumiov2alpha1.CiliumResolvedPolicy]
}

// NewCiliumResolvedPolicyLister returns a new CiliumResolvedPolicyLister.
func NewCiliumResolvedPolicyLister(indexer cache.Indexer) CiliumResolvedPolicyLister {
	return &ciliumResolvedPolicyLister{listers.New[*ciliumiov2alpha1.CiliumResolvedPolicy](indexer, ciliumiov2alpha1.Resource("ciliumresolvedpolicy"))}
}
