// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

package v2alpha1

import (
	"github.com/cilium/cilium/pkg/identity"
	slimv1 "github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/meta/v1"
	"github.com/cilium/cilium/pkg/policy/api"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:nonNamespaced
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:resource:categories={cilium,ciliumresolved},singular="ciliumresolvedpolicy",path="ciliumresolvedpolicies",scope="Cluster",shortName={crp}
// +kubebuilder:printcolumn:JSONPath=".metadata.creationTimestamp",name="Age",type=date
// +kubebuilder:storageversion

// CiliumResolvedPolicy is a Kubernetes third-party resource representing pre-computed policy
// with identity mappings for reduced computational overhead on Cilium agents.
// It is generated by a centralized controller that watches CNP, CCNP, and KNP resources,
// computes the policy rules and their affected identities, and distributes them to agents.
// This centralized approach significantly reduces resource overhead and API server load
// in large clusters by eliminating redundant policy computation across all agents.
//
// The CiliumResolvedPolicy is cluster-scoped and contains the pre-computed mapping between
// network policy rules and affected identities, allowing agents to efficiently apply
// the policies without having to perform the expensive identity resolution themselves.
type CiliumResolvedPolicy struct {
	// +k8s:openapi-gen=false
	// +deepequal-gen=false
	metav1.TypeMeta `json:",inline"`
	// +k8s:openapi-gen=false
	// +deepequal-gen=false
	metav1.ObjectMeta `json:"metadata"`

	// Spec is the specification of the CiliumResolvedPolicy
	//
	// +kubebuilder:validation:Required
	Spec *CiliumResolvedPolicySpec `json:"spec,omitempty"`

	// Status is the status of the CiliumResolvedPolicy
	Status CiliumResolvedPolicyStatus `json:"status,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// CiliumResolvedPolicyList is a list of CiliumResolvedPolicy objects
type CiliumResolvedPolicyList struct {
	// +k8s:openapi-gen=false
	// +deepequal-gen=false
	metav1.TypeMeta `json:",inline"`
	// +k8s:openapi-gen=false
	// +deepequal-gen=false
	metav1.ListMeta `json:"metadata"`

	// Items is a list of CiliumResolvedPolicies
	Items []CiliumResolvedPolicy `json:"items"`
}

// CiliumResolvedPolicySpec is the specification of the CiliumResolvedPolicy
type CiliumResolvedPolicySpec struct {
	// PolicyRef is a reference to source policy which was resolved
	// +kubebuilder:validation:Required
	PolicyRef PolicyRef `json:"policyRef"`

	// RuleSelector is the selector used to select rules from the source policy
	// +kubebuilder:validation:Required
	RuleSelector *ResolvedSelector `json:"ruleSelector"`

	// Ingress rule selector is the list of ingress rules that were selected from the source policy.
	// It can be empty if no ingress rules were selected.
	// +kubebuilder:validation:Required
	IngressRuleSelectors []ResolvedSelector `json:"ingressRuleSelectors"`

	// Egress rule selector is the list of egress rules that were selected from the source policy.
	// It can be empty if no egress rules were selected.
	// +kubebuilder:validation:Required
	EgressRuleSelectors []ResolvedSelector `json:"egressRuleSelectors"`

	// rule is the rule configured in the source policy
	// +kubebuilder:validation:Required
	Rule *api.Rule `json:"rule"`
}

// PolicyRef is a reference to the source policy which was resolved
type PolicyRef struct {
	// Name is the name of the policy
	// +kubebuilder:validation:Required
	Name string `json:"name"`

	// Namespace is the namespace of the policy
	// For CCNP this will be empty as it's cluster-scoped
	// +kubebuilder:validation:Required
	Namespace string `json:"namespace"`

	// Type is the type of the policy
	// CNP: CiliumNetworkPolicy
	// CCNP: CiliumClusterwideNetworkPolicy
	// KNP: Kubernetes NetworkPolicy
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=CNP;CCNP;KNP
	Type string `json:"type"`

	// UID is the UID of the source policy
	// +kubebuilder:validation:Optional
	UID string `json:"uid,omitempty"`

	// ResourceVersion is the resource version of the source policy
	// +kubebuilder:validation:Optional
	ResourceVersion string `json:"resourceVersion,omitempty"`
}

type ResolvedSelector struct {
	// Selector is the endpoint selector that was used to determine the identities
	// +kubebuilder:validation:Required
	Selector *api.EndpointSelector `json:"selector"`

	// Identities is the list of identities that match the selector.
	// This list can be empty if the selector does not match any identities.
	// +kubebuilder:validation:Optional
	Identities []identity.NumericIdentity `json:"identities"`
}

// CiliumResolvedPolicyStatus is the status of a CiliumResolvedPolicy
type CiliumResolvedPolicyStatus struct {
	// Processed indicates whether the policy has been processed by the central controller
	Processed bool `json:"processed,omitempty"`

	// ProcessingTime is the timestamp when the policy was processed
	ProcessingTime *slimv1.Time `json:"processingTime,omitempty"`
}
